#  __  __ _            __  __             _
# |  \/  (_)          |  \/  |           (_)
# | \  / |_ _ __   ___| \  / | __ _ _ __  _  __ _
# | |\/| | | '_ \ / _ \ |\/| |/ _` | '_ \| |/ _` |
# | |  | | | | | |  __/ |  | | (_| | | | | | (_| |
# |_|  |_|_|_| |_|\___|_|  |_|\__,_|_| |_|_|\__,_|
#
# Author: MineManiaUK Staff

kerb:
  client_name: ""
  server_port: 5000
  server_address: ""
  server_certificate_path: ""
  client_certificate_path: ""
  password: ""
  max_wait_time_millis: 400

database:
  connection_string: ""
  database_name: ""